### ISSUE TITLE
For large N amount of function calls on rando(a,b). rando(a,b) no longer returns a continues distribution.

### ISSUE THREAD

**Issue by Smoggert** [nastyox/Rando.js#10]
Case: Large N in loop with rando(a,b)
for (i=0; max=N; i++)
rando(a,b);

if N >>> 100
rando(a,b) is not returning a continues distribution of random numbers, for large groups of N.

Tested with following code:
```
<script src = "https://randojs.com/2.0.0.js"></script>

<script type="text/javascript">
var diceSize = 25
var diceCount = [], distrCount = []
var rolls = 1000000
for(var i = 0; i < diceSize; i++)
{
	diceCount[i] = 0;
}

for(var i = 0; i < rolls; i++){
	diceCount[rando(0,diceSize-1)]++;
}

for(var i = 0; i < diceCount.length; i++)
{
	distrCount[i] = (diceCount[i]*100/rolls);
}

console.log("Dicerolls:", diceCount);
console.log("Diceroll distr:", distrCount, "%");
</script>
```

**Comment by nastyox** [comment]
Thank you for including your code and making your problem clear and concise! I've reviewed your code and have to say that I'm not seeing an issue here. Rando.js' distribution is easily on par with that of `Math.random()`, and [`Math.random()` is rated for "approximately uniform distribution"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random).

**Compare Rando.js' distribution:**
```JavaScript
var SLOTS = 25, ROLLS = 1000000, diceCount = [], distrCount = [];

for(var i = 0; i < SLOTS; i++) diceCount[i] = 0;
for(var i = 0; i < ROLLS; i++) diceCount[rando(0, SLOTS - 1)]++;
for(var i = 0; i < diceCount.length; i++) distrCount[i] = diceCount[i] * 100 / ROLLS;

console.log("Rolls per slot:", diceCount, "Percent per slot:", distrCount, "Max gap:", (Math.max(...distrCount) - Math.min(...distrCount)) + "%");
```

**Against `Math.random()`'s distribution:**
```JavaScript
var SLOTS = 25, ROLLS = 1000000, diceCount = [], distrCount = [];

for(var i = 0; i < SLOTS; i++) diceCount[i] = 0;
for(var i = 0; i < ROLLS; i++) diceCount[Math.floor(Math.random() * SLOTS)]++;
for(var i = 0; i < diceCount.length; i++) distrCount[i] = diceCount[i] * 100 / ROLLS;

console.log("Rolls per slot:", diceCount, "Percent per slot:", distrCount, "Max gap:", (Math.max(...distrCount) - Math.min(...distrCount)) + "%");
```

Not all slots are going to have the exact same number of hits, but they'll be close. Just like if you were to flip a coin 1000 times, you might get "heads" 503 times instead of 500. That's just how randomness goes. We know pretty much what to expect, but we our prediction won't be exactly correct all the time. A certain amount of leeway is expected. I'm going to go ahead and close this issue out, but please leave a comment if I've misunderstood anything, and I'll gladly have a look. Thank you for taking the time to interact with the project and get in touch with me about it! I appreciate everyone that takes an interest in it, and I hope it serves you well.

**Comment by Smoggert** [comment]
Small variations are fine, if I run this code on a browser (Firefox & Chrome)
(N = 1kk, diceSize = 6 - save my cpu for a bit)
I get following results:
Rando Dicerolls Firefox:
Array(6) [ 1940533, 1850618, 1550197, 1550340, 1553162, 1555150 ] diceTest.html:27:10
Array(6) [ 19.40533, 18.50618, 15.50197, 15.5034, 15.53162, 15.5515 ]%  diceTest.html:28:10
Chrome:
(6) [1939108, 1850725, 1551914, 1552313, 1555761, 1550179]
(6) [19.39108, 18.50725, 15.51914, 15.52313, 15.55761, 15.50179] %

Significant deviations on the lower end of your distribution and the effect is consistent. (at least on my end)
 Maybe it's related with how browsers handle it? I dunno.

Meanwhile math.random is giving a uniform distribution.

**Comment by nastyox** [comment]
**Got it!** I was using Chrome to test, and it was uniform there. However, the cryptographic algorithm _is_ browser-dependent. In other browsers, I can see what you're talking about, and I've isolated the source of this issue. Filling a `Uint32Array` with random values results in a possible number range of 0 to 4294967295. I was throwing away the first and last digit to account for the fact that the first digit could never be 5-9 and the last digit was sightly less likely to be 6-9. That's great, but the fact the second digit of the range's max is a 2 means we're more likely to get a number starting with a 0, 1, or 2 after discarding the first and last digit rather than 3-9. That's where the tendency towards smaller numbers is coming from. The same idea propagates down the line with each digit of the max that isn't a 9. To fix this, I've capped the numbers that Rando.js will consider at 3999999999 (still discarding the first digit). 

I've updated all plain JavaScript versions so all projects currently using Rando.js will see this improvement without needing to change anything, and I've released a new npm version addressing this. Everything meets expectations now. Thank you very much for letting me know about this!
