### ISSUE TITLE
Dependency error on a React project

### ISSUE THREAD

**Issue by Beerbill** [nastyox/Rando.js#11]
When i try to use it on a react project it fail to find your dependencies:

Error: Unable to resolve module `crypto` from `node_modules/@nastyox/rando.js/rando-min.js`: crypto could not be found within the project.

**Comment by shadowtime2000** [comment]
This is may be because it doesn't exist in the `package.json` (try using an npm dependency graph app to verify this) but I can't really tell from just that because the `package.json` isn't commited. ig one short term solution would be to just install `crypto`.

**Comment by nastyox** [comment]
I set up a new React project with npm per the instructions [here](https://reactjs.org/docs/create-a-new-react-app.html#create-react-app) and then installed Rando.js on the project with npm. After that, I pasted the following line:
`const randojs = require('@nastyox/rando.js'), rando = randojs.rando, randoSequence = randojs.randoSequence;`

in the project's `src/App.js` file, and everything worked for me as shown here:

![React Rando.js sample code](http://randojs.com/images/extra/react-sample-code.png)

![React Rando.js sample](http://randojs.com/images/extra/react-sample-live.png)

For at least 4 years, `crypto` has [been a built-in Node module](https://www.npmjs.com/package/crypto), but [it's possible for node to be built without it](https://nodejs.org/api/crypto.html). If you don't have `crypto`, installing it with `npm install crypto` might just give you an empty package because it might assume it was already built-in when you installed node. Instead, you may need to reinstall node altogether to make sure you're up to date on your built-in packages.

**Fair warning:** If you try to Google this error, you may find [this page](https://github.com/auth0/react-native-auth0/issues/276) or [this page](https://github.com/brix/crypto-js/issues/256). These are talking about a package called [`crypto-js`](https://www.npmjs.com/package/crypto-js/v/3.3.0), which Rando.js does NOT use. Rando.js uses [`crypto`](https://www.npmjs.com/package/crypto), so those search results are not applicable to your situation at all.

Please let me know if this was helpful. I'm happy to have a deeper look at this if you give me more information. Otherwise, if you get past this issue on your own or with the suggestions I've already made, make sure to post a reply here so everyone knows how you did it. I'll mark this issue as closed for now, but I'll reopen it if needed.

**Comment by shadowtime2000** [comment]
@nastyox Support for ESM modules should be added to the package. I could do that once #12 is resolved.
