### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by alfianandinugraha** [nastyox/Rando.js#14]
Hello, does this package has support of typescript ? I was tried with ESM, but getting this error
![image](https://user-images.githubusercontent.com/34809276/135791125-ea7d8cc2-4c89-4550-8ccf-68354e2b6faa.png)

**Comment by nastyox** [comment]
The import statement you have is not referring to any actual code unless you have [installed Rando.js with npm](https://www.npmjs.com/package/@nastyox/rando.js) OR you have added the script tag ```<script src="https://randojs.com/2.0.0.js"></script>``` to your page.

**Comment by alfianandinugraha** [comment]
I was installed 
![image](https://user-images.githubusercontent.com/34809276/135794754-a404b693-e3ea-4255-98e0-16f8c0765443.png)

But still getting error on WebStorm:
![image](https://user-images.githubusercontent.com/34809276/135794737-4c384f9c-53bf-4de5-90cf-4aa86dac3290.png)

This project for example usage, maybe I will use Rando.js for Vue / Express with typescript

**Comment by nastyox** [comment]
That looks like the root of the issue. Rando.js is written specifically to allow its parameters to be of any type. It detects parameter type and provides a corresponding return value. Because of this, it can't have strict parameter types and cannot be used with typescript.

I will consider making a typescript version of Rando.js in the future, but it will need to be used differently, so it will have different documentation altogether. In the meantime, if you want to grab Rando.js' source code and work on a typescript version yourself, please feel free.
